### ISSUE TITLE
Calculation of offset_rel_t0 incorrect

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/uclahedp#12]
When calculating the offset indices relative to t0, the offsets should be: offset = offset_range + t0indarr - ta.  The ta = t0indarr - mint0ind is missing.

**Comment by pheuer** [comment]
I see what you mean: this is necessary because the offset indices are applied AFTER we take the slice ta:tb. I have added a  " - ta" to each offset_a and offset_b and will push that shortly.
