### ISSUE TITLE
Axes saved in reverse order

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/uclahedp#13]
When setting the keyword strict_axes=True in bdotRawtoFull, the makeAxes function returns an array in reverse order (pos to neg) if the step size value (e.g. "dx") is <0.  The axis is then saved this way, preventing, for example, DataView from correctly displaying the axis.

It's not clear if the axis needs to be ordered this way when extracting data (or displaying it), or if it can be re-ordered within makeAxes.  If the former, then the data may need to be correspondingly flipped to make everything consistent.

**Comment by pheuer** [comment]
I don't think the order of the axes should matter: fuzzyGrid shouldnt' care, and strictGrid doesn't use the axes at all. Therefore it should just be a simple matter of fixing the way the axes are constructed in makeAxes. 

I've implemented this in the commit below by sorting the axes before returning them in makeAxes. Let me know if this causes some other problem I'm not foreseeing. 

fbb4ab34028b0558713e94866b5b9ccad62c4734


fbb4ab34028b0558713e94866b5b9ccad62c4734
