### ISSUE TITLE
readAttrs not reading attributes correctly

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/uclahedp#14]
For some reason, the readAttrs function in hdf.py is not reading correctly the "Ny", "dy", and "y0" attributes from run33_xy_setB_gridB.hdf5.  I suspect this has to do with how these attributes are being decoded, but I don't know why only these ones have issues.

**Comment by pheuer** [comment]
Where is this error being thrown? When you try to run bdotRawToFull?

**Comment by dschaeffer17** [comment]
Yes, this is during bdotRawtoFull, but it doesn't throw an error - it just isn't reading those attributes correctly.  They're correct in the file (as seen in HDFView), but for some reason not in python.

**Comment by pheuer** [comment]
How does that manifest: it reads the wrong value in?

**Comment by dschaeffer17** [comment]
Correct.  For run33, for example, Ny=26 and dy=1, but python reads in Ny=1, dy=0.

**Comment by pheuer** [comment]
Great: I found the bug. It was an error in lapd.readPosArray() for the NI_XYZ drive that was ignoring the Y direction. Should now be fixed as of

a1b51af011ce4ecc31fef1cc6715aaf8b8a78d70
