### ISSUE TITLE
Auto-Select TS Mode

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/uclahedp#22]
Suggest calculating scattering parameter alpha=1/k lambda_debye and using that to auto select mode (collective or non-collective).  Though, is there an advantage to breaking it up like this, since the collective version will also return non-collective spectrum?

**Comment by pheuer** [comment]
I broke these up explicitly because I wanted to compare the different models to make sure they worked in the appropriate limits, but for a more narrow final version of the code I agree that this isn’t necessary.
