### ISSUE TITLE
Minor: modify text outputs in processing routines

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/uclahedp#7]
Suggest modifying what text is printed during lapdToRaw, tdiodeRawToFull, and bdotRawToFull.  If verbose=False, should print basic steps being taken and time remaining.  If verbose=True, should print reminding diagnostic texts.

Currently, always prints large dictionaries that aren't very helpful (see end for example).  If verbose=False, doesn't print time remaining statements.

Example diagnostic output that should only print if verbose=True:
{'probe': ("b'LAPD_C6'", b''), 'calib_date': ("b'1/?/2019'", b''), 'size': ("b'3mm'", b''), 'naxes': (3, b''), 'nturns': (10, b''), 'xarea': (10.58647, b'mm^2'), 'yarea': (15.17866, b'mm^2'), 'zarea': (12.61607, b'mm^2'), 'notes': (nan, b''), 'run': (24, b''), 'date': ("b'1/19/2019'", b''), 'index': (24, b''), 'drive': ("b'xyz_krishna'", b''), 'plane': ("b'xy'", b''), 'motion_controller': ("b'NI_XYZ'", b''), 'motion_ind': (0, b''), 'motion_receptacle': (1, b''), 'gridded': (1, b''), 'gain': (10, b''), 'port': ("b'19E'", b''), 'xpos': (-111, b'cm'), 'ypos': (-111, b'cm'), 'zpos': (-111, b'cm'), 'xpol': (1, b''), 'ypol': (1, b''), 'zpol': (1, b''), 'xdir': ("b'X'", b''), 'ydir': ("b'Y'", b''), 'zdir': ("b'Z'", b''), 'roll': (0, b''), 'probe_origin_x': (0, b'cm'), 'probe_origin_y': (0, b'cm'), 'probe_origin_z': (-617.5, b'cm'), 'rot_center_x': (55, b'cm'), 'rot_center_y': (0, b'cm'), 'rot_center_z': (0, b'cm'), 'xatten': (46, b'dB'), 'yatten': (46, b'dB'), 'zatten': (50, b'dB'), 'probe_type': ("b'bdot'", b''), 'nchan': (3, b''), 'digitizer': ("b'SIS crate'", b''), 'adc': ("b'SIS 3305'", b''), 'brd1': (1, b''), 'brd2': (1, b''), 'brd3': (1, b''), 'chan1': (2, b''), 'chan2': (3, b''), 'chan3': (4, b''), 'cable_length': (25, b''), 'datafile': ("b'run24_xz_setC_gridB_laser'", b''), 'chamber': ("b'LAPD'", b''), 'pressure': (5e-05, b'Gas Fill'), 'gas': ("b'H'", b''), 'B0_target': (300, b''), 'lab6_pulse': (4, b'LaB6'), 'lab6_laser_timing': (7, b''), 'lab6_discharge_voltage': (170, b''), 'lab6_heater_voltage': (80, b''), 'lab6_discharge_current': (2.25, b''), 'lab6_heater_current': (450, b''), 'lapd_notes': (nan, b''), 'laser': ("b'Peening'", b'Laser'), 'laser_shot_num': ("b'N/A'", b''), 'laser_energy': (15, b''), 'laser_pulse_width': (16, b''), 'laser_h_spot_size': (0.2, b''), 'laser_v_spot_size': (0.2, b''), 'laser_notes': (nan, b''), 'target_material': (nan, b'Target'), 'target_height': (nan, b''), 'target_angle': (nan, b''), 'translate_per_rot': (nan, b''), 'rot_per_shot': (nan, b''), 'shots_per_pos': (nan, b''), 'target_xpos': (nan, b''), 'target_ypos': (nan, b''), 'target_zpos': (nan, b''), 'target_notes': (nan, b''), 'dt': (8e-10, b's')}
['xarea', 'yarea', 'zarea', 'xatten', 'yatten', 'zatten', 'gain', 'xpol', 'ypol', 'zpol', 'roll', 'probe_origin_x', 'probe_origin_y', 'probe_origin_z', 'dt', 'nturns', 'rot_center_x', 'rot_center_y', 'rot_center_z']

**Comment by pheuer** [comment]
Agreed in general: this current dictionary dump is temporary in an attempt to figure out what's going wrong with issue #2, which has been inconsistent and difficult to replicate. I wasn't typically passing a verbose keyword that deep into the subroutines (csvtools.missingKeywords()). My preference would be to just leave this text dump in as mandatory for now, and then remove it in a month or so if issue #2 either gets resolved or stops occuring?

**Comment by pheuer** [comment]
I haven't had issues with #2 for a while, so I've removed this printout for now and am closing this issue.
