### ISSUE TITLE
Auto-create relevant directories

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/uclahedp#9]
Noticed that lapdToRaw does not auto create the RAW directory to save the HDF5 file.  Suggest in general all directories for hd5 processing be auto-created if necessary.

**Comment by pheuer** [comment]
This should definitely be done: I'll add it to the list.

**Comment by pheuer** [comment]
Added this functionality to the lapd.py, tdiode.py, and bdot.py processes via the newly added hdf.requireDirs() function.
